### PR TITLE
🚫VIM

### PR DESCRIPTION
**Pull request by armcburney**

### CODE REVIEW

**Review by pmbauer — APPROVED** [review]

**Review by domingohui — APPROVED** [review]

**Review by jaronoff97 — APPROVED** [review]
lgtm.

**Review by lpan — CHANGES_REQUESTED** [review]
https://github.com/lpan/dotfiles/blob/master/files/files.json @AndrewMcBurney can you update this file as well. My Python script reads from this JSON file to determine what files are linked to what path. Otherwise LGTM 👍

**Review by GaurabAryal — CHANGES_REQUESTED** [review]
Revert the changes, tnx

**Comment by armcburney** [comment]
lol @GaurabAryal, you can't even request changes - only suggest them. smh 🅱️🅾️ℹ️

screen shot 2018-03-21 at 4 16 35 pm

**Comment by lpan** [comment]
sad boi react only

**Comment by armcburney** [comment]
😤

**Comment by jaronoff97** [comment]
👿

**Pull request closed without merging**
